name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Срабатывает при пуше тега, начинающегося с "v"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update version
        run: |
          pip install -r requirements.txt
          python src/path2markdown/update_version.py ${{ github.ref_name }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --icon=resources/icon.ico --name=Path2Markdown src/path2markdown/main.py

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build installer
        # Предполагается, что setup.iss находится в папке installer/
        run: "& 'C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe' installer\\setup.iss"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: installer/Output/Path2Markdown_Setup.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Debug: Check artifact location
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Unzip artifact
        run: |
          unzip Path2Markdown/installer.zip -d extracted

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: extracted/Path2Markdown_Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
